Implement RAC style library
RockefellerArchiveCenter/cartographer_frontend pull request #235
Opened 2024-06-11 15:30 UTC by helrond

Implements the RAC style library.

A number of changes to the tests were also required. I'm not sure exactly why these were failing locally but not in CI but they are passing locally now.

I also removed some extraneous infrastructure that we don't use.

A couple of things to look at in the future:
- Updating the app to React 18, and updating the testing infrastructure at the same time.
- Looking at the overall structure of the app, and possibly bringing it more in line with how DIMES is structured.
- Reviewing the interaction pattern on the MapForm page - there are a lot of independent save actions (title, children, publish) that are happening which should probably just be combined into a single save method.

2024-06-14 20:12 UTC, HaSistrunk commented
I know this site is not widely used, but if we want to lock in some best practices, we should stay away from disabled buttons. It's much better UX and better for a11y to let someone click a button regardless, and then return a form error or whatever error message if they haven't entered the correct information instead of disabling the button until the user types something in. So that would apply to:
- "Save Title" button for adding a new map
- "Fetch from ArchivesSpace" when getting an arrangement map component

2024-06-20 17:38 UTC, helrond commented
Good call Hannah - to me that falls under reviewing interaction patterns because those disabled buttons are there in an attempt to make the current interaction patterns less breakable.

2024-06-21 15:31 UTC, HaSistrunk requested changes
This is looking really good to me! I'm having trouble getting an arrangement map created because of fetching issues, so I haven't reviewed everything in the UI, but hopefully others can review that. A couple other things:
1. The modal size on desktop is pretty big for the content that's in there, particularly just for short confirmation messages. It may make sense to add styles to make those smaller to look a little better.
2. I'm not sure if this is an existing bug in Cartographer now, but I noticed if I go to "Add New Map", type in a title, and hit "Save", it displays the map on the homepage. If I'm understanding the logic correctly, we'd only want the new map to appear in the arrangement maps on the homepage once the map is published, right?

2024-06-21 15:31 UTC, HaSistrunk commented on src/components/Modals.js
> +                {error}
```suggestion
                Error message: {error}
```

2024-06-21 15:31 UTC, HaSistrunk commented on src/components/MapList.js
> +              </span>
1. The "Edit" link and "Delete" button need to be programmatically associated with the arrangement map title that they act on. Adding an `aria-label` that gives them the name "Edit { item.title }" or "Delete { item.title }" would do the trick.

2024-06-21 15:31 UTC, HaSistrunk commented on src/components/Modals.js
>  ConfirmModal.propTypes = {
The modal should close with the ESC key, so we'll want to add that option, which I see should be [available in reactstrap](https://reactstrap.github.io/?path=/docs/components-modal--modal).

2024-06-21 15:31 UTC, HaSistrunk commented on src/components/Header.js
> +        </nav>
Is this actually navigation? I could see an argument that it is a main function of the site and should be moved out of the header nav and be, like, a large button after the `h1` similar to how the Edit Map page has the "Publish Map" button.

2024-06-21 15:31 UTC, HaSistrunk commented on src/components/Modals.js
> +                {error}
I'm pretty certain that for `role=alert` to work, there has to be an empty div that already exists on the page with `role='alert'` (which is assertive and interrupts the screen reader) or `role='status'` (which is polite and waits for the screen reader to finish what it's doing and then reads the new content) assigned to it. Then, when the error appears dynamically, it is added to that div that is already in the DOM and the changes inside it are announced to the screen reader. This is something we need to update in the Style Guide (I [added an issue](https://github.com/RockefellerArchiveCenter/styles/issues/211)).

2024-06-21 15:31 UTC, HaSistrunk commented on public/index.html
> +    <link rel='stylesheet' href='https://assets.rockarch.org/v0.10.0/main.min.css'>
You'll also want to replace the local favicon with the one from the style library: https://assets.rockarch.org/assets/img/favicon.ico

2024-06-21 15:31 UTC, HaSistrunk commented on src/components/MapList.js
> +      <div className='card'>
```suggestion
      <div className='card card--container'>
```

2024-06-21 15:31 UTC, HaSistrunk commented on src/index.css
> +}
```suggestion
.mapList__item {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 12px 20px;
  border-bottom: 1px solid #5c5c5c;
}
```

2024-06-26 16:04 UTC, helrond commented on src/components/Modals.js
> +                {error}
@HaSistrunk I think I got this right, but wouldn't mind a double-check.

2024-06-26 16:54 UTC, helrond commented
Thanks for your detailed review @HaSistrunk!

Regarding your second point above - yes, that is intended behavior. Maps should be able to be created independently of being published. If we didn't show the map until it was published there would be no way of editing a map once it was created if it wasn't immediately published.

2024-06-27 13:44 UTC, HaSistrunk commented on src/components/Modals.js
> +                {error}
Yes! I tested and this works well.

2024-06-27 13:44 UTC, HaSistrunk approved these changes
This is looking really good to me!

2024-06-28 15:05 UTC, p-galligan approved these changes

2024-06-28 15:56 UTC, kemartin2015 approved these changes

2024-06-28 17:18 UTC, daremiyo approved these changes

2024-07-01 16:08 UTC, merged